FROM golang:latest as build

WORKDIR /go/src/submane-server/api
COPY ./api/go.mod .
COPY ./api/go.sum .
RUN go mod download
COPY ./api .
ENV GO_ENV=production

RUN go build -o server .
ENTRYPOINT ["/server web"]
