FROM golang:latest AS build

WORKDIR /go/src/submane-server/api
COPY ./api/go.mod .
COPY ./api/go.sum .
RUN go mod download
COPY ./api .
ENV GO_ENV=development

# -oはoutput
RUN go build -o /go/bin/app
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
