version: '3.7'
services:
  echo:
    container_name: echo
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: build
    volumes:
      - ./api:/go/src/submane-server/api
    ports:
      - "1323:1323"
    command: go run server.go
  postgres:
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: submane_db
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres-data:/var/lib/pgadmin
    ports:
      - 5433:5432
volumes:
  postgres-data:
    driver: local
