FROM golang:latest AS build

WORKDIR /go/src/submane-server/api
COPY ./api/go.mod .
COPY ./api/go.sum .
RUN go mod download
COPY ./api .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o /server ./api
ENTRYPOINT ["/main web"]
