version: '3.7'
services:
  echo:
    container_name: echo
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: build
    volumes:
      - ./api:/go/src/github.com/shun0211/sabumane-server/api
    ports:
      - "1323:1323"
    command: realize start --run --no-config
  postgres:
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DATABASE: sabumane_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres-data
    ports:
      - 5433:5432
volumes:
  postgres-data:
    driver: local
